import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src="https://genaiollms.com/meta-loader.v1.js"
          data-token="546efcfd299a"
          data-lang="auto"
          data-scope="entire"
          data-variant="stable"
          data-endpoint="http://100.90.105.18:3000/meta"
          strategy="beforeInteractive"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script
          src="https://genaiollms.com/embed.v1.js"
          data-token="546efcfd299a"
          data-lang="auto"
          data-scope="entire"
          data-variant="stable"
          data-jsonld="auto"
          data-endpoint="http://100.90.105.18:3000/render"
          data-log-endpoint="http://100.90.105.18:3000/log"
          strategy="afterInteractive"
        />
        {children}
      </body>
    </html>
  );
}
